name: taqwim
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+2

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.19
  bloc: ^8.1.1
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.3
  equatable: ^2.0.5
  firebase_core:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^2.1.0
  flutter_ringtone_player: ^3.2.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  hijri_picker:
    path: assets/appPackages/hijri_picker-master
  #jhijri_picker: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.3.0
  quickalert: ^1.0.1
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  url_launcher: ^6.1.10
  volume_control: ^0.1.5
  intl:
  share_plus: ^7.0.1
  flutter_super_html_viewer: ^0.1.0
  flutter_image_slideshow: ^0.1.5
  flutter_rounded_date_picker: ^3.0.3
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/audio/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
